spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:db_todo}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    defer-datasource-initialization: true

openapi:
  service:
    title: to-do-list
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /todo/v3/api-docs
  swagger-ui:
    path: /todo/swagger-ui.html